name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: "Call API"
        run: |
          curl -X POST https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE_ID }}/query \
          -H "Notion-Version: 2021-08-16" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.NOTION_KEY }}" \
          -d "{}" > ./src/data.json

      - name: Build project
        run: npm run build

      - name: "Copy raw data"
        run: "cp ./src/data.json ./dist/data.json"

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
